name: Integração "Beco Escuro Filmes"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    name: SonarCloud
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan
      continue-on-error: true
      run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=gabruw_beco-escuro-filmes -Dsonar.organization=Snyp -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
